config/routes.rb
Groster::Application.routes.draw do
  devise_for :users

  resources :profiles

  match '/contributors' => 'profiles#contributors'
  match '/pending' => "profiles#pending"

  root :to => 'profiles#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :email, :github, :name, :blog, :text_editor, :twitter, :linkedin
  validates_uniqueness_of :email, :blog, :twitter, :github

  def key
    {0 => :pending, 1=> :active, 2=> :contributor}  
  end

  def self.pending
    self.where(status: 0).all.shuffle
  end
  
  def self.active
    self.where(status: 1).all.shuffle
  end

  def self.contributors
    self.where(status: 2).all.shuffle    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, 
  :rememberable, 
  :trackable, 
  :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, :only => [:pending, :edit, :update, :destroy]

  def pending
    @profiles = Profile.pending
  end

  def index
    @profiles = Profile.active
  end

  def contributors
    @profiles = Profile.contributors
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(params[:profile])
    @profile.status = 0
    if @profile.save
      redirect_to action: "index", notice: 'Profile was successfully created.' 
    else
      render action: "new"
    end
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(params[:profile])
      redirect_to root_path, notice: 'Profile was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  
  def name_cleaner(name)
    if name.length > 17
      "#{name.split[0]} #{name.split[-1][0].upcase}"
    else
      "#{name.split[0]} #{name.split[-1]}"
    end
  end


  def fancy_twitter_link(twitter)
    "<iframe allowtransparency='true' frameborder='0' scrolling='no'
  src='//platform.twitter.com/widgets/follow_button.html?screen_name=#{twitter}'
  style='width:300px; height:20px;'></iframe>".html_safe
  end

  def fancy_github_link(github)
    "<a target='_blank'
     href='https://github.com/#{github}' 
     class='muted'>
    <i class='icon-github'></i> #{github}</a>".html_safe
  end

  def fancy_linkedin(profile)
    a = profile.name.split
    "<a target='_blank' class='test-inverse' href=#{valid_linkedin(profile.linkedin)}><i class='icon-linkedin'></i> #{a[0][0].upcase}. #{a[-1].capitalize}</a>".html_safe
  end

  def valid_linkedin(input)
    if input.include?("http")
      input
    else
      "http://linkedin.com/in/#{input}"
    end
  end

  def fancy_web_link(url)
    "<a target='_blank' class='text-error' href=#{clean_link(url)} ><i class='icon-bookmark text-error'></i> blog</a>".html_safe
  end

  def clean_link(url)
    if url.include?("http")
      url
    else
      "http://#{url}"
    end
  end

  def pretty_url(url)
    url.gsub("http://","")
  end

   def hidden_email(email)
     "#{email[0..email.index("@")]}****.com"
   end

  def hidden_phone(phone)
    "(***)-***-#{phone[-4..-1]}"
  end


end

app/views/layouts/_footer.html.erb
<%= debug(params) if Rails.env.development? %>
  <div class="row" >
    <div class="navbar navbar-fixed-bottom" id="header">
      <div class="container">
        <div class="row">
          <div class="span3">
            <h5>
              <%= link_to "View Project on Github",
               "https://github.com/blairand/gschoolroster" %>
            </h5>
          </div>          

          <div class="span3">
            <h5>
              <%= link_to "Contributors", contributors_path %>
            </h5>
          </div>

          <div class="span3">
            <% if user_signed_in? %>
              <p class="lead">
                Signed in as <%= current_user.email %>,
                <%= link_to "sign out?", destroy_user_session_path, :method => :delete %>
              </p>
              <% else %>
              
            <% end %>
          </div>
        </div>
      </div>
    </div> <!-- /.container -->

</div>

app/views/layouts/_navbar.html.erb
<div class="row">
  <div class="navbar-wrapper">
    <div class="navbar navbar-fixed-top" id="header">
      <div class="container">
        <h1 id="header_text">
          <%= link_to "gSchoolRoster", root_path %>
          <small>
            <%= link_to " click here to add yourself...", new_profile_path %>
          </small>
        </h1>      
      </div>
    </div> <!-- /.container -->
  </div><!-- /.navbar-wrapper -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gRoster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <style type="text/css">
    body {padding-top: 80px; padding-bottom: 80px;}
    .thumbnails > li {
    float: left;
    margin-bottom: 18px;
    margin-left: 20px;
    height: 275px;
        }

    #header {
      background-color:#CAE2EC;
      opacity: .93;
      box-shadow: 0px 0px 5px #444;
      :;
        }
    #header_text > a {
      color: #fff;
    }

  </style>

  <%= javascript_include_tag "application" %>
  <script type="text/javascript" charset="utf-8">
      window.twttr = (function (d,s,id) {
          var t, js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
          js.src="//platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
          return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
      }(document, "script", "twitter-wjs"));
  </script>
  <script type="text/javascript" src="http://octophile.com/widgets.js">
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Franklin Webber XVI" %>
  </div>
  <div class="field">
    <%= f.label :BlogURL %>
    <%= f.text_field :blog, placeholder: "http://blairbuilds.herokuapp.com/" %>
  </div>
  <div class="field">
    <%= f.label :email %>(this is private, only used for gravatar picture)
    <%= f.text_field :email, placeholder: "skijumpboy69@aol.com" %>
  </div>
  
  <div class="field">
    <%= f.label :twitter %>
    <div class="input-prepend">
      <span class="add-on">@</span>
      <%= f.text_field :twitter, id: "prependedInput", placeholder: "steveklabnik" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :github %>
    <div class="input-prepend">
      <span class="add-on">@</span>
      <%= f.text_field :github, id: "prependedInput", placeholder: "steveklabnik" %>
    </div>
  </div>
<!--   <div class="field">
    <%= f.label :text_editor %><br />
    <%= f.text_field :text_editor %>
  </div> -->
    <div class="field">
      <%= f.label :linkedin_UserName %> 
      <%= f.text_field :linkedin, placeholder: "andersonblair" %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_list_item.html.erb
<li class="span3">
  <div class="thumbnail">
    <%= gravatar_image_tag(profile.email, class: "img-circle") %>
    <h3 class=""><%= link_to profile.name.split[0], profile %></h3>
    <p>
      <ul class="unstyled">
        <% unless profile.twitter == "" %>
          <li>
            <%= fancy_twitter_link(profile.twitter) %>
          </li>
          <% else %>
           <li><small>No tweets</small></li>          
        <% end %>

        <% unless profile.github == "" %>
            <li>
              <%= fancy_github_link(profile.github) %>
            </li>
            <% else %>
           <li><small>No github...</small></li>
        <% end %>

        <% unless profile.blog == "" %>
          <li>
            <%= fancy_web_link(profile.blog) %>
          </li>
          <% else %>
           <li><small>No blog...</small></li>
        <% end %>

        <% unless profile.linkedin == "" %>
          <li>
            <%= fancy_linkedin(profile) %>
          </li>
          <% else %>
           <li><small>No linkedin...</small></li>
        <% end %>

        <% if user_signed_in? %>
        <li class="divider"></li>
        <li class="nav-header">Update:</li>
        <li><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <li><%= link_to 'Edit', edit_profile_path(profile) %></li>
        <% else %>
        <% end %>
      </ul>
    </p>
  </div>
</li>

app/views/profiles/contributors.html.erb
<div class="container">
  <h1>Contributors</h1>
  <ul class="thumbnails">
    <% @profiles.each do |profile| %>
      <li class="span4">
        <%= gravatar_image_tag( profile.email, alt: profile.name , class: 'img-rounded thumbnail', gravatar: { size: 300 }) %>  
        <h1><b><%= profile.name %></b></h1>
        <a href="https://twitter.com/<%= profile.twitter %>" class="twitter-follow-button" data-show-count="true" data-size="large" data-lang="en">Follow <%= profile.twitter %></a>

        <% unless profile.github == "" %>
          <a href="https://github.com/<%= profile.github %>" class="github-follow-button">Follow On GitHub</a>
          <script type="text/javascript" src="http://octophile.com/widgets.js"></script>
        <% end %>

        <p class="lead"><%= fancy_web_link(profile.blog) %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="container">
<div class="row"></div>
  <ul class="thumbnails">
    <% @profiles.each_with_index do |profile,i| %>
      <li class="span3 clearfix">
        <div class="thumbnail">
          <%= gravatar_image_tag(profile.email, class: "img-circle") %>
          <h3 class=""><%= link_to name_cleaner(profile.name), profile %></h3>
          <p>
            <ul class="unstyled profile-details">
              <% unless profile.twitter == "" %>
                <li>
                  <%= fancy_twitter_link(profile.twitter) %>
                </li>
                <% else %>
                 <li><small>No tweets</small></li>          
              <% end %>

              <% unless profile.github == "" %>
                  <li>
                    <%= fancy_github_link(profile.github) %>
                  </li>
                  <% else %>
                 <li><small>No github...</small></li>
              <% end %>

              <% unless profile.blog == "" %>
                <li>
                  <%= fancy_web_link(profile.blog) %>
                </li>
                <% else %>
                 <li><small>No blog...</small></li>
              <% end %>

              <% unless profile.linkedin == "" %>
                <li>
                  <%= fancy_linkedin(profile) %>
                </li>
                <% else %>
                 <li><small>No linkedin...</small></li>
              <% end %>

              <% if user_signed_in? %>
              <li class="divider"></li>
              <li class="nav-header">Update:</li>
              <li><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li><%= link_to 'Edit', edit_profile_path(profile) %></li>
              <% else %>
              <% end %>
            </ul>
          </p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/profiles/new.html.erb
<div class="span5 offset3">
<h1>New profile</h1>
<%= render 'form' %>
</div>

app/views/profiles/pending.html.erb
<% @profiles.each_with_index do |profile,i| %>
<div class="span2">
  <ul>
    <%= gravatar_image_tag(profile.email, class: "img-circle") %>
    <li><%= profile.status %></li>
    <li><%= link_to name_cleaner(profile.name), profile %></li>
    <li><%= profile.twitter %></li>
    <li><%= profile.github %></li>
    <li><%= profile.blog %></li>
    <li><%= profile.linkedin %></li>
    <li>
    <%= link_to 'Destroy', profile, 
    method: :delete, 
    data: { confirm: 'Are you sure?' } %>
    </li>
    <li><%= link_to 'Edit', edit_profile_path(profile) %></li>
  </ul>
</div>
<% end %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="span3">
  <%= gravatar_image_tag( @profile.email, alt: @profile.name , class: 'img-rounded', gravatar: { size: 300 }) %>  
</div>
<div class="span5">
  <%= link_to 'Edit', edit_profile_path(@profile), class:"btn btn-mini" %>  
  <h1><b><%= @profile.name %></b></h1>

  <a href="https://twitter.com/<%= @profile.twitter %>" class="twitter-follow-button" data-show-count="true" data-size="large" data-lang="en">Follow @<%= @profile.twitter %></a>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<% unless @profile.github == "" %>
<a href="https://github.com/<%= @profile.github %>" class="github-follow-button">Follow On GitHub</a>
<script type="text/javascript" src="http://octophile.com/widgets.js"></script>
<% end %>


<p class="lead"><%= fancy_web_link(@profile.blog) %></p>
</div>